import type { OracleCase } from './types';

/**
 * Hand-derived rheumatology classification oracles.
 * Point totals are counted from the published tables cited in `source`.
 * These cases were NOT reverse-engineered from calculator output.
 */
export const wave7RheumClassOracles: OracleCase[] = [
  // ── 2010 ACR/EULAR RA (Aletaha 2010): joints 0–5 + serology 0–3 + APR 0–1 + duration 0–1; ≥6 classifies ──
  {
    calcId: 'acr-eular-ra-2010',
    description: '>10 joints 5 + high-positive RF/ACPA 3 + abnormal APR 1 + duration ≥6 weeks 1 = 10; entry met → classified',
    inputs: {
      entrySwollen: true,
      betterAlt: false,
      joints: 'gt10',
      serology: 'high',
      apr: 'abnormal',
      duration: 'ge6',
    },
    expect: { score: 10, riskLevel: 'high' },
    source: 'Aletaha D et al. Ann Rheum Dis 2010; Table 3 (PMID 21285115)',
  },
  {
    calcId: 'acr-eular-ra-2010',
    description: '1 large joint 0 + negative serology 0 + normal APR 0 + duration <6 weeks 0 = 0; not classified',
    inputs: {
      entrySwollen: false,
      betterAlt: false,
      joints: '1-large',
      serology: 'neg',
      apr: 'normal',
      duration: 'lt6',
    },
    expect: { score: 0, riskLevel: 'low' },
    source: 'Aletaha D et al. Ann Rheum Dis 2010; Table 3 (PMID 21285115)',
  },

  // ── 2019 EULAR/ACR SLE: highest per domain; ANA entry; ≥10 and ≥1 clinical ──
  {
    calcId: 'eular-acr-sle-2019',
    description: 'ANA + ACLE 6 + joint involvement 6 = 12 classified',
    inputs: {
      ana: true,
      constitutional: 'none',
      hematologic: 'none',
      neuro: 'none',
      mucocutaneous: 'acle',
      serosal: 'none',
      msk: 'joints',
      renal: 'none',
      apl: 'none',
      complement: 'none',
      sleAbs: 'none',
    },
    expect: { score: 12, riskLevel: 'high' },
    source: 'Aringer M et al. Ann Rheum Dis 2019; weighted domain table (PMID 30936257)',
  },
  {
    calcId: 'eular-acr-sle-2019',
    description: 'ANA + fever 2 only = 2; below 10, not classified',
    inputs: {
      ana: true,
      constitutional: 'fever',
      hematologic: 'none',
      neuro: 'none',
      mucocutaneous: 'none',
      serosal: 'none',
      msk: 'none',
      renal: 'none',
      apl: 'none',
      complement: 'none',
      sleAbs: 'none',
    },
    expect: { score: 2, riskLevel: 'low' },
    source: 'Aringer M et al. Ann Rheum Dis 2019; constitutional fever = 2 (PMID 30936257)',
  },

  // ── 2016 ACR/EULAR Sjögren: FS 3, SSA 3, OSS 1, vBS 1, Schirmer 1, UWS 1; ≥4 ──
  {
    calcId: 'acr-eular-sjogren-2016',
    description: 'Anti-SSA/Ro 3 + Schirmer 1 = 4 classified with sicca entry',
    inputs: { entrySicca: true, focusScore: false, ssa: true, oss: false, vanBijsterveld: false, schirmer: true, saliva: false },
    expect: { score: 4, riskLevel: 'high' },
    source: 'Shiboski CH et al. Ann Rheum Dis 2016; weighted items (PMID 26989107)',
  },
  {
    calcId: 'acr-eular-sjogren-2016',
    description: 'SSA 3 alone = 3; below 4, not classified',
    inputs: { entrySicca: true, focusScore: false, ssa: true, oss: false, vanBijsterveld: false, schirmer: false, saliva: false },
    expect: { score: 3, riskLevel: 'low' },
    source: 'Shiboski CH et al. Ann Rheum Dis 2016 (PMID 26989107)',
  },

  // ── 2013 ACR/EULAR SSc: proximal skin 9 sufficient; else additive ≥9 ──
  {
    calcId: 'acr-eular-ssc-2013',
    description: 'Skin thickening proximal to MCP of both hands = 9, classified',
    inputs: { skin: 'proximal', fingertip: 'none', telangiectasia: false, nailfold: false, pahIld: false, raynaud: false, sscAbs: false },
    expect: { score: 9, riskLevel: 'high' },
    source: 'van den Hoogen F et al. Ann Rheum Dis 2013; proximal skin = 9 (PMID 24122180)',
  },
  {
    calcId: 'acr-eular-ssc-2013',
    description: 'Raynaud 3 + SSc antibodies 3 + abnormal nailfold 2 = 8, not classified',
    inputs: { skin: 'none', fingertip: 'none', telangiectasia: false, nailfold: true, pahIld: false, raynaud: true, sscAbs: true },
    expect: { score: 8, riskLevel: 'low' },
    source: 'van den Hoogen F et al. Ann Rheum Dis 2013 (PMID 24122180)',
  },
  {
    calcId: 'acr-eular-ssc-2013',
    description: 'Raynaud 3 + Abs 3 + nailfold 2 + telangiectasia 2 = 10 classified',
    inputs: { skin: 'none', fingertip: 'none', telangiectasia: true, nailfold: true, pahIld: false, raynaud: true, sscAbs: true },
    expect: { score: 10, riskLevel: 'high' },
    source: 'van den Hoogen F et al. Ann Rheum Dis 2013 (PMID 24122180)',
  },

  // ── 2012 ACR/EULAR PMR: stiffness 2, hip 1, seronegative 2, no peripheral 1; clinical ≥4 ──
  {
    calcId: 'acr-eular-pmr-2012',
    description: 'Morning stiffness 2 + RF/ACPA negative 2 = 4; clinical algorithm ≥4 classified',
    inputs: {
      stiffness: true,
      hip: false,
      seronegative: true,
      noPeripheralSynovitis: false,
      usShoulderHip: false,
      usBothShoulders: false,
      algorithm: 'clinical',
    },
    expect: { score: 4, riskLevel: 'high' },
    source: 'Dasgupta B et al. Arthritis Rheum 2012; Table 1 (PMID 22302501)',
  },
  {
    calcId: 'acr-eular-pmr-2012',
    description: 'Stiffness 2 only = 2; clinical algorithm not classified',
    inputs: {
      stiffness: true,
      hip: false,
      seronegative: false,
      noPeripheralSynovitis: false,
      usShoulderHip: false,
      usBothShoulders: false,
      algorithm: 'clinical',
    },
    expect: { score: 2, riskLevel: 'low' },
    source: 'Dasgupta B et al. Arthritis Rheum 2012 (PMID 22302501)',
  },

  // ── 2022 ACR/EULAR GPA: PR3 +5, nasal +3, eos −4; ≥5 ──
  {
    calcId: 'acr-eular-gpa-2022',
    description: 'PR3 +5 + bloody nasal discharge +3 = 8 classified (entry met)',
    inputs: {
      entryVasculitis: true,
      nasal: true,
      cartilage: false,
      hearing: false,
      pr3: true,
      nodules: false,
      granuloma: false,
      sinusImaging: false,
      gn: false,
      mpo: false,
      eosinophils: false,
    },
    expect: { score: 8, riskLevel: 'high' },
    source: 'Robson JC et al. Ann Rheum Dis 2022; GPA item weights (PMID 35110333)',
  },
  {
    calcId: 'acr-eular-gpa-2022',
    description: 'PR3 +5 + eosinophilia −4 = 1; below 5, not classified',
    inputs: {
      entryVasculitis: true,
      nasal: false,
      cartilage: false,
      hearing: false,
      pr3: true,
      nodules: false,
      granuloma: false,
      sinusImaging: false,
      gn: false,
      mpo: false,
      eosinophils: true,
    },
    expect: { score: 1, riskLevel: 'low' },
    source: 'Robson JC et al. Ann Rheum Dis 2022 (PMID 35110333)',
  },

  // ── 2022 ACR/EULAR MPA: MPO +6, nasal −3; ≥5 ──
  {
    calcId: 'acr-eular-mpa-2022',
    description: 'MPO-ANCA +6 = 6 classified (entry met)',
    inputs: {
      entryVasculitis: true,
      nasal: false,
      mpo: true,
      ild: false,
      gn: false,
      pr3: false,
      eosinophils: false,
    },
    expect: { score: 6, riskLevel: 'high' },
    source: 'Suppiah R et al. Ann Rheum Dis 2022; MPA item weights (PMID 35110332)',
  },
  {
    calcId: 'acr-eular-mpa-2022',
    description: 'MPO +6 + nasal discharge −3 = 3; not classified',
    inputs: {
      entryVasculitis: true,
      nasal: true,
      mpo: true,
      ild: false,
      gn: false,
      pr3: false,
      eosinophils: false,
    },
    expect: { score: 3, riskLevel: 'low' },
    source: 'Suppiah R et al. Ann Rheum Dis 2022 (PMID 35110332)',
  },

  // ── 2022 ACR/EULAR EGPA: airway +3, polyps +3, eos +5; ≥6 ──
  {
    calcId: 'acr-eular-egpa-2022',
    description: 'Obstructive airway disease +3 + eosinophils +5 = 8 classified',
    inputs: {
      airway: true,
      polyps: false,
      mononeuritis: false,
      eosinophils: true,
      extravascularEos: false,
      pr3: false,
      hematuria: false,
    },
    expect: { score: 8, riskLevel: 'high' },
    source: 'Grayson PC et al. Ann Rheum Dis 2022; EGPA item weights (PMID 35110331)',
  },
  {
    calcId: 'acr-eular-egpa-2022',
    description: 'Obstructive airway disease +3 only = 3; not classified',
    inputs: {
      airway: true,
      polyps: false,
      mononeuritis: false,
      eosinophils: false,
      extravascularEos: false,
      pr3: false,
      hematuria: false,
    },
    expect: { score: 3, riskLevel: 'low' },
    source: 'Grayson PC et al. Ann Rheum Dis 2022 (PMID 35110331)',
  },

  // ── 2022 ACR/EULAR GCA: TAB/halo +5, ESR/CRP +3; ≥6 and age ≥50 ──
  {
    calcId: 'acr-eular-gca-2022',
    description: 'Age 70 + positive TAB +5 + ESR/CRP +3 = 8 classified',
    inputs: {
      age: 70,
      morningStiffness: false,
      claudication: false,
      headache: false,
      scalp: false,
      abnormalTA: false,
      visualLoss: false,
      axillary: false,
      petAorta: false,
      esrCrp: true,
      tabHalo: true,
    },
    expect: { score: 8, riskLevel: 'high' },
    source: 'Ponte C et al. Arthritis Rheumatol 2022; GCA item weights (PMID 36350123)',
  },
  {
    calcId: 'acr-eular-gca-2022',
    description: 'Age 70 + TAB/halo +5 only = 5; below 6, not classified',
    inputs: {
      age: 70,
      morningStiffness: false,
      claudication: false,
      headache: false,
      scalp: false,
      abnormalTA: false,
      visualLoss: false,
      axillary: false,
      petAorta: false,
      esrCrp: false,
      tabHalo: true,
    },
    expect: { score: 5, riskLevel: 'low' },
    source: 'Ponte C et al. Arthritis Rheumatol 2022 (PMID 36350123)',
  },

  // ── 2022 ACR/EULAR TAK: female +1, claudication +2, bruit +2, 1 territory +1 = 6; age ≤60 + imaging ──
  {
    calcId: 'acr-eular-tak-2022',
    description: 'Female 1 + claudication 2 + bruit 2 + 1 territory 1 = 6 classified (age 30, LVV imaging)',
    inputs: {
      age: 30,
      imagingLVV: true,
      sex: 'female',
      angina: false,
      claudication: true,
      bruit: true,
      reducedUEPulse: false,
      carotid: false,
      bpDiff: false,
      territories: 1,
      pairedArteries: false,
      abdominalAorta: false,
    },
    expect: { score: 6, riskLevel: 'high' },
    source: 'Grayson PC et al. Ann Rheum Dis 2022; TAK item weights (PMID 36350125)',
  },
  {
    calcId: 'acr-eular-tak-2022',
    description: 'Female 1 + 1 territory 1 = 2; below 5, not classified',
    inputs: {
      age: 30,
      imagingLVV: true,
      sex: 'female',
      angina: false,
      claudication: false,
      bruit: false,
      reducedUEPulse: false,
      carotid: false,
      bpDiff: false,
      territories: 1,
      pairedArteries: false,
      abdominalAorta: false,
    },
    expect: { score: 2, riskLevel: 'low' },
    source: 'Grayson PC et al. Ann Rheum Dis 2022 (PMID 36350125)',
  },

  // ── CASPAR 2006: current psoriasis 2, RF− 1, nail 1, dactylitis 1, new bone 1; ≥3 + entry ──
  {
    calcId: 'caspar-psa',
    description: 'Current psoriasis 2 + negative RF 1 = 3 classified',
    inputs: {
      entryInflammatory: true,
      psoriasis: 'current',
      nail: false,
      rfNeg: true,
      dactylitis: false,
      juxtaBone: false,
    },
    expect: { score: 3, riskLevel: 'high' },
    source: 'Taylor W et al. Arthritis Rheum 2006; CASPAR table (PMID 16583464)',
  },
  {
    calcId: 'caspar-psa',
    description: 'Current psoriasis 2 only = 2; below 3, not classified',
    inputs: {
      entryInflammatory: true,
      psoriasis: 'current',
      nail: false,
      rfNeg: false,
      dactylitis: false,
      juxtaBone: false,
    },
    expect: { score: 2, riskLevel: 'low' },
    source: 'Taylor W et al. Arthritis Rheum 2006 (PMID 16583464)',
  },

  // ── ASAS axial SpA ──
  {
    calcId: 'asas-axspa',
    description: 'Entry + sacroiliitis + IBP → imaging arm classified',
    inputs: {
      entryBackPain: true,
      ibp: true,
      arthritis: false,
      enthesitis: false,
      uveitis: false,
      dactylitis: false,
      psoriasis: false,
      ibd: false,
      nsaidResponse: false,
      familySpA: false,
      hlaB27: false,
      crp: false,
      sacroiliitis: true,
    },
    expect: { score: 'Imaging arm', riskLevel: 'high' },
    source: 'Rudwaleit M et al. Ann Rheum Dis 2009; ASAS axial SpA (PMID 19734190)',
  },
  {
    calcId: 'asas-axspa',
    description: 'Entry + HLA-B27 only (no other features, no sacroiliitis) → not classified (need ≥2 other features)',
    inputs: {
      entryBackPain: true,
      ibp: false,
      arthritis: false,
      enthesitis: false,
      uveitis: false,
      dactylitis: false,
      psoriasis: false,
      ibd: false,
      nsaidResponse: false,
      familySpA: false,
      hlaB27: true,
      crp: false,
      sacroiliitis: false,
    },
    expect: { score: 'Not classified', riskLevel: 'low' },
    source: 'Rudwaleit M et al. Ann Rheum Dis 2009 (PMID 19734190)',
  },

  // ── ASAS peripheral SpA ──
  {
    calcId: 'asas-perispa',
    description: 'Entry + psoriasis (category A) → classified',
    inputs: {
      entryPeripheral: true,
      psoriasis: true,
      ibd: false,
      infection: false,
      hlaB27: false,
      uveitis: false,
      sacroiliitis: false,
      arthritis: false,
      enthesitis: false,
      dactylitis: false,
      ibp: false,
      familySpA: false,
    },
    expect: { score: 'Peripheral SpA classified', riskLevel: 'high' },
    source: 'Rudwaleit M et al. Ann Rheum Dis 2011; ASAS peripheral SpA (PMID 21177297)',
  },

  // ── Yamaguchi AOSD: 4 major + 1 minor = 5 with ≥2 major, no exclusions ──
  {
    calcId: 'yamaguchi-aosd',
    description: '4 major + sore throat 1 minor = 5 classified (exclusions negative)',
    inputs: {
      fever: true,
      arthralgia: true,
      rash: true,
      leukocytosis: true,
      soreThroat: true,
      nodesSpleen: false,
      lft: false,
      seronegative: false,
      exclInfection: false,
      exclMalignancy: false,
      exclRheum: false,
    },
    expect: { score: 5, riskLevel: 'high' },
    source: 'Yamaguchi M et al. J Rheumatol 1992; ≥5 including ≥2 major (PMID 1306111)',
  },
  {
    calcId: 'yamaguchi-aosd',
    description: '4 major + 1 minor but infection exclusion → not classified; score still 5',
    inputs: {
      fever: true,
      arthralgia: true,
      rash: true,
      leukocytosis: true,
      soreThroat: true,
      nodesSpleen: false,
      lft: false,
      seronegative: false,
      exclInfection: true,
      exclMalignancy: false,
      exclRheum: false,
    },
    expect: { score: 5, riskLevel: 'low' },
    source: 'Yamaguchi M et al. J Rheumatol 1992; exclusions mandatory (PMID 1306111)',
  },

  // ── Fautrel AOSD: score = major count; ≥4 major classifies ──
  {
    calcId: 'fautrel-aosd',
    description: '4 majors (fever, arthralgia, pharyngitis, PMN≥80%) = 4 classified',
    inputs: {
      spikeFever: true,
      arthralgia: true,
      transientErythema: false,
      pharyngitis: true,
      pmn80: true,
      glycFerritin: false,
      typicalRash: false,
      leukocytosis: false,
    },
    expect: { score: 4, riskLevel: 'high' },
    source: 'Fautrel B et al. J Rheumatol 2001; ≥4 major (PMID 11838846)',
  },
  {
    calcId: 'fautrel-aosd',
    description: '3 majors + 0 minors = 3 not classified',
    inputs: {
      spikeFever: true,
      arthralgia: true,
      transientErythema: false,
      pharyngitis: true,
      pmn80: false,
      glycFerritin: false,
      typicalRash: false,
      leukocytosis: false,
    },
    expect: { score: 3, riskLevel: 'low' },
    source: 'Fautrel B et al. J Rheumatol 2001; 3 major needs 2 minor (PMID 11838846)',
  },

  // ── 2017 EULAR/ACR IIM: Jo-1 3.9 + heliotrope 3.1 + enzymes 1.3 = 8.3 without biopsy ──
  {
    calcId: 'eular-acr-myositis-2017',
    description: 'Without biopsy: Jo-1 3.9 + heliotrope 3.1 + elevated enzymes 1.3 = 8.3 classified (≥5.5)',
    inputs: {
      path: 'without',
      ageOnset: 'lt18',
      proxUE: false,
      proxLE: false,
      neckFlex: false,
      proxGtDist: false,
      skin: 'heliotrope',
      dysphagia: false,
      jo1: true,
      enzymes: true,
      bxEndomysial: false,
      bxPerimysial: false,
      bxPerifascicular: false,
      bxRimmed: false,
    },
    expect: { score: 8.3, tolerance: 0.1, riskLevel: 'high' },
    source: 'Lundberg IE et al. Ann Rheum Dis 2017; Table 2 without-biopsy weights (PMID 29135554)',
  },
  {
    calcId: 'eular-acr-myositis-2017',
    description: 'Without biopsy: Jo-1 3.9 only = 3.9; below 5.5, not classified',
    inputs: {
      path: 'without',
      ageOnset: 'lt18',
      proxUE: false,
      proxLE: false,
      neckFlex: false,
      proxGtDist: false,
      skin: 'none',
      dysphagia: false,
      jo1: true,
      enzymes: false,
      bxEndomysial: false,
      bxPerimysial: false,
      bxPerifascicular: false,
      bxRimmed: false,
    },
    expect: { score: 3.9, tolerance: 0.1, riskLevel: 'low' },
    source: 'Lundberg IE et al. Ann Rheum Dis 2017; anti-Jo-1 without biopsy = 3.9 (PMID 29135554)',
  },

  // ── 2023 ACR/EULAR APS: unprovoked VTE 3 + persistent LAC 5; clinical ≥3 and lab ≥3 ──
  {
    calcId: 'acr-eular-aps-2023',
    description: 'Unprovoked VTE 3 + persistent LAC 5 = clinical 3 lab 5, combined 8 classified',
    inputs: {
      vte: 'unprovoked',
      arterial: 'none',
      microvascular: 'none',
      obstetric: 'none',
      valve: 'none',
      thrombocytopenia: false,
      lac: 'persistent',
      aclIgg: 'none',
      aclIgm: 'none',
      b2Igg: 'none',
      b2Igm: 'none',
    },
    expect: { score: 8, riskLevel: 'high' },
    source: 'Barbhaiya M et al. Arthritis Rheumatol 2023; VTE without high-risk profile = 3, persistent LAC = 5 (PMID 37609646)',
  },
  {
    calcId: 'acr-eular-aps-2023',
    description: 'Unprovoked VTE 3 + single LAC 1 = clinical 3 lab 1, combined 4 not classified (lab <3)',
    inputs: {
      vte: 'unprovoked',
      arterial: 'none',
      microvascular: 'none',
      obstetric: 'none',
      valve: 'none',
      thrombocytopenia: false,
      lac: 'single',
      aclIgg: 'none',
      aclIgm: 'none',
      b2Igg: 'none',
      b2Igm: 'none',
    },
    expect: { score: 4, riskLevel: 'low' },
    source: 'Barbhaiya M et al. Arthritis Rheumatol 2023; need ≥3 lab points (PMID 37609646)',
  },

  // ── Sydney APS ──
  {
    calcId: 'sapporo-sydney-aps',
    description: 'Thrombosis + LAC persistent ≥12 weeks → Sydney APS classified',
    inputs: { thrombosis: true, obstetric: false, lac: true, acl: false, b2gpi: false, persistent: true },
    expect: { score: 'APS classified', riskLevel: 'high' },
    source: 'Miyakis S et al. J Thromb Haemost 2006; Sydney revision (PMID 16905515)',
  },

  // ── ICBD Behçet: ocular 2, oral 2, genital 2, skin/neuro/vascular/pathergy 1; ≥4 ──
  {
    calcId: 'icbd-behcet',
    description: 'Oral aphthosis 2 + genital aphthosis 2 = 4 classified',
    inputs: { ocular: false, oral: true, genital: true, skin: false, neuro: false, vascular: false, pathergy: false },
    expect: { score: 4, riskLevel: 'high' },
    source: 'ICBD. J Eur Acad Dermatol Venereol 2014; oral 2 + genital 2 (PMID 23913606)',
  },
  {
    calcId: 'icbd-behcet',
    description: 'Oral 2 + skin 1 = 3; below 4, not classified',
    inputs: { ocular: false, oral: true, genital: false, skin: true, neuro: false, vascular: false, pathergy: false },
    expect: { score: 3, riskLevel: 'low' },
    source: 'ICBD. J Eur Acad Dermatol Venereol 2014 (PMID 23913606)',
  },

  // ── ISG Behçet: oral + 2 of genital/eye/skin/pathergy ──
  {
    calcId: 'isg-behcet',
    description: 'Recurrent oral + genital + eye → ISG classified',
    inputs: { oral: true, genital: true, eye: true, skin: false, pathergy: false },
    expect: { score: 'Behçet classified', riskLevel: 'high' },
    source: 'International Study Group for Behçet’s Disease. Lancet 1990 (PMID 1970380)',
  },
  {
    calcId: 'isg-behcet',
    description: 'Oral + genital only (1 extra) → not classified',
    inputs: { oral: true, genital: true, eye: false, skin: false, pathergy: false },
    expect: { score: 'Not classified', riskLevel: 'low' },
    source: 'International Study Group for Behçet’s Disease. Lancet 1990 (PMID 1970380)',
  },
];
