import type { OracleCase } from './types';

export const wave7FillinsOracles: OracleCase[] = [
  {
    calcId: 'kfre-8',
    description:
      '70M, eGFR 30, ACR 200 mg/g, albumin 3.5, phosphorus 4.8, HCO₃ 22, Ca 8.8: Tangri 2011 8-var LP ≈ 1.392 → 5-year risk ≈ 23.2% (S₀ 0.9365)',
    inputs: {
      age: 70,
      sex: 'M',
      egfr: 30,
      acr: 200,
      albumin: 3.5,
      phosphorus: 4.8,
      bicarbonate: 22,
      calcium: 8.8,
    },
    expect: { score: 23.2, tolerance: 1.0 },
    source: 'Tangri N et al. JAMA 2011 PMID 21482743; 8-variable coefficients with development centering and educational NA S₀ 5y 0.9365',
  },
  {
    calcId: 'gds-15',
    description: 'All non-depressive responses (reverse items Yes, forward items No) score 0',
    inputs: {
      gds1: 'yes',
      gds2: 'no',
      gds3: 'no',
      gds4: 'no',
      gds5: 'yes',
      gds6: 'no',
      gds7: 'yes',
      gds8: 'no',
      gds9: 'no',
      gds10: 'no',
      gds11: 'yes',
      gds12: 'no',
      gds13: 'yes',
      gds14: 'no',
      gds15: 'no',
    },
    expect: { score: 0, riskLevel: 'normal' },
    source: 'Sheikh & Yesavage Clin Gerontol 1986 PMID 3335884; GDS-15 reverse items 1,5,7,11,13',
  },
  {
    calcId: 'gds-15',
    description: 'Five depressive forward items (2,3,4,6,8 Yes) score 5 (mild band)',
    inputs: {
      gds1: 'yes',
      gds2: 'yes',
      gds3: 'yes',
      gds4: 'yes',
      gds5: 'yes',
      gds6: 'yes',
      gds7: 'yes',
      gds8: 'yes',
      gds9: 'no',
      gds10: 'no',
      gds11: 'yes',
      gds12: 'no',
      gds13: 'yes',
      gds14: 'no',
      gds15: 'no',
    },
    expect: { score: 5, riskLevel: 'moderate' },
    source: 'Sheikh & Yesavage 1986; cutoff ≥5 possible depression, 5–9 mild',
  },
  {
    calcId: 'rbaux',
    description: 'Age 40 + TBSA 20% + no inhalation = 60',
    inputs: { age: 40, tbsa: 20, inhalation: false },
    expect: { score: 60 },
    source: 'Osler T et al. J Trauma 2010 PMID 20381254; rBaux = age + %TBSA + 17×inhalation',
  },
  {
    calcId: 'rbaux',
    description: 'Age 40 + TBSA 20% + inhalation = 77',
    inputs: { age: 40, tbsa: 20, inhalation: true },
    expect: { score: 77 },
    source: 'Osler T et al. J Trauma 2010 PMID 20381254',
  },
  {
    calcId: 'ranson-pancreatitis',
    description: 'No Ranson criteria = 0 (low)',
    inputs: {
      age: false,
      wbc: false,
      glu: false,
      ldh: false,
      ast: false,
      hct: false,
      bun: false,
      ca: false,
      pao2: false,
      base: false,
      fluid: false,
    },
    expect: { score: 0, riskLevel: 'low' },
    source: 'Ranson JH et al. Surg Gynecol Obstet 1974 PMID 4834279',
  },
  {
    calcId: 'ranson-pancreatitis',
    description: 'Three admission flags (age, WBC, glucose) = 3 (moderate)',
    inputs: {
      age: true,
      wbc: true,
      glu: true,
      ldh: false,
      ast: false,
      hct: false,
      bun: false,
      ca: false,
      pao2: false,
      base: false,
      fluid: false,
    },
    expect: { score: 3, riskLevel: 'moderate' },
    source: 'Ranson 1974; 3–4 moderate severity band',
  },
  {
    calcId: 'improve-dd',
    description: 'Current cancer (+2) + age ≥60 (+1) + D-dimer ≥2× ULN (+2) = 5',
    inputs: {
      priorVte: false,
      thrombophilia: false,
      paralysis: false,
      cancer: true,
      immobility: false,
      icu: false,
      age: 70,
      ddimer: true,
    },
    expect: { score: 5, riskLevel: 'high' },
    source: 'IMPROVE + Gibson IMPROVEDD; cancer 2, age ≥60 1, D-dimer 2',
  },
  {
    calcId: 'peps-4',
    description: 'Age 40 (−2) only, remaining items absent = −2 (very low)',
    inputs: {
      age: 40,
      sex: 'F',
      crd: false,
      hr80: false,
      chestDyspnea: false,
      hormone: false,
      priorVte: false,
      syncope: false,
      immobility: false,
      spo2: false,
      calf: false,
      peLikely: false,
    },
    expect: { score: -2, riskLevel: 'low' },
    source: 'Roy PM et al. JAMA Cardiol 2021 PMID 33656522 Table 3; age <50 = −2; very low if <0',
  },
  {
    calcId: 'absi-burn',
    description: 'Male (0) + age 30 (2) + no inhalation/FT + TBSA 20% (2) = 4',
    inputs: { sex: 0, age: 30, inhalation: false, fullThickness: false, tbsa: 20 },
    expect: { score: 4 },
    source: 'Tobiasen J et al. Ann Emerg Med 1982 PMID 7074538',
  },
];
