import type { OracleCase } from './types';

export const wave7HighuseOracles: OracleCase[] = [
  // ---------------------------------------------------------------- MAGGIC
  {
    calcId: 'maggic-hf',
    description:
      'Zero-risk profile: age <55, female, NYHA I, EF ≥40, SBP ≥150, BMI ≥30, Cr <90, no DM/COPD/smoke, recent HF, on BB and ACEI/ARB = 0',
    inputs: {
      age: 50,
      lvef: 50,
      sbp: 150,
      bmi: 32,
      creatinine: 70,
      nyha: 1,
      male: false,
      diabetes: false,
      copd: false,
      smoker: false,
      hfOver18mo: false,
      noBb: false,
      noAcei: false,
    },
    expect: { score: 0, riskLevel: 'low' },
    source: 'Pocock SJ et al. Eur Heart J. 2013;34:1404-13 — integer MAGGIC; lowest cells are 0 points (Table 3 / heartfailurerisk.org).',
  },
  {
    calcId: 'maggic-hf',
    description: 'Male (+1) + NYHA II (+2) + not on beta-blocker (+3) = 6, other cells zero',
    inputs: {
      age: 50,
      lvef: 50,
      sbp: 150,
      bmi: 32,
      creatinine: 70,
      nyha: 2,
      male: true,
      diabetes: false,
      copd: false,
      smoker: false,
      hfOver18mo: false,
      noBb: true,
      noAcei: false,
    },
    expect: { score: 6, riskLevel: 'low' },
    source: 'Pocock 2013 integer score: male 1, NYHA II 2, no β-blocker 3.',
  },

  // ---------------------------------------------------------------- PRAM
  {
    calcId: 'pram',
    description: 'SpO2 <92 (2) + wheeze 3 + air entry 3, retractions 0, scalene 0 = 8',
    inputs: { retractions: 0, scalene: 0, airEntry: 3, wheeze: 3, spo2: 2 },
    expect: { score: 8, riskLevel: 'high' },
    source: 'Ducharme FM et al. J Pediatr. 2008;152:476-80 — PRAM: SpO2 <92 = 2, wheeze 0–3, air entry 0–3 (PMID 19047225).',
  },
  {
    calcId: 'pram',
    description: 'All components 0 = 0 (mild)',
    inputs: { retractions: 0, scalene: 0, airEntry: 0, wheeze: 0, spo2: 0 },
    expect: { score: 0, riskLevel: 'low' },
    source: 'Ducharme 2008 PRAM minimum is 0.',
  },

  // ---------------------------------------------------------------- HITS
  {
    calcId: 'hits-ipv',
    description: 'All four items Never (1) = 4, negative screen',
    inputs: { hurt: 1, insult: 1, threaten: 1, scream: 1 },
    expect: { score: 4, riskLevel: 'low' },
    source: 'Sherin KM et al. Fam Med. 1998;30:508-512 — HITS items scored 1–5; minimum 4; positive ≥10 (PMID 9704230).',
  },
  {
    calcId: 'hits-ipv',
    description: 'All four items Sometimes (3) = 12, positive screen',
    inputs: { hurt: 3, insult: 3, threaten: 3, scream: 3 },
    expect: { score: 12, riskLevel: 'high' },
    source: 'Sherin 1998 — four items × 3 = 12, which is ≥10 (positive).',
  },

  // ---------------------------------------------------------------- WIfI
  {
    calcId: 'wifi-diabetic-foot',
    description: 'W2-I2-fI1 is Mills clinical stage 4 (high 1-year amputation risk), not a moderate integer sum',
    inputs: { wound: 2, ischemia: 2, infection: 1 },
    expect: { score: 4, riskLevel: 'high' },
    source: 'Mills JL Sr et al. J Vasc Surg. 2014;59:220-34 — WIfI W2-I2-fI1 maps to High (clinical stage 4) on the 64-cell amputation-risk grid (PMID 24126108).',
  },
  {
    calcId: 'wifi-diabetic-foot',
    description: 'W0-I0-fI0 is clinical stage 1 (very low)',
    inputs: { wound: 0, ischemia: 0, infection: 0 },
    expect: { score: 1, riskLevel: 'low' },
    source: 'Mills 2014 WIfI — W0-I0-fI0 is very low (clinical stage 1).',
  },

  // ---------------------------------------------------------------- CARG
  {
    calcId: 'carg-chemo',
    description: 'Age ≥72 (2) + anemia (3) + falls (3) = 8 intermediate; other items absent',
    inputs: {
      age72: true,
      giGu: false,
      standardDose: false,
      polychemo: false,
      anemia: true,
      crclLow: false,
      hearing: false,
      falls: true,
      limitedWalk: false,
      medsHelp: false,
      socialDec: false,
    },
    expect: { score: 8, riskLevel: 'moderate' },
    source: 'Hurria A et al. J Clin Oncol. 2011;29:3457-65 — CARG-TT: age ≥72 = 2, anemia = 3, ≥1 fall = 3; 6–9 = intermediate (~52% G3–5) (PMID 21860000).',
  },
  {
    calcId: 'carg-chemo',
    description: 'No CARG risk factors = 0 (low)',
    inputs: {
      age72: false,
      giGu: false,
      standardDose: false,
      polychemo: false,
      anemia: false,
      crclLow: false,
      hearing: false,
      falls: false,
      limitedWalk: false,
      medsHelp: false,
      socialDec: false,
    },
    expect: { score: 0, riskLevel: 'low' },
    source: 'Hurria 2011 — score range 0–23; 0–5 is low risk.',
  },

  // ---------------------------------------------------------------- ACEF II
  {
    calcId: 'acef-ii',
    description: 'Age 70 / EF 50, Cr 1.0 (not >2), not emergency, HCT 40 (≥36) → 70/50 = 1.4',
    inputs: { age: 70, ef: 50, cr: 1.0, emergency: false, hct: 40 },
    expect: { score: 1.4, tolerance: 0.01 },
    source: 'Ranucci M et al. Eur Heart J. 2018;39:2183-9 — ACEF II = age/EF + 2 if Cr>2 + 3 if emergency + 0.2 per HCT point <36 (PMID 28498904).',
  },
  {
    calcId: 'acef-ii',
    description: 'Age 70 / EF 50 + Cr 2.5 (+2) + emergency (+3) + HCT 40 (0) = 1.4 + 2 + 3 = 6.4',
    inputs: { age: 70, ef: 50, cr: 2.5, emergency: true, hct: 40 },
    expect: { score: 6.4, tolerance: 0.01 },
    source: 'Ranucci 2018 ACEF II add-ons: Cr >2.0 mg/dL = +2; emergency surgery = +3.',
  },

  // ---------------------------------------------------------------- ISTH-SSC BAT
  {
    calcId: 'isth-ssc-bat',
    description: 'All 14 domains 0 in a male = 0 (normal)',
    inputs: {
      sex: 'male',
      epistaxis: 0,
      cutaneous: 0,
      minorWounds: 0,
      oralCavity: 0,
      gi: 0,
      hematuria: 0,
      toothExtraction: 0,
      surgery: 0,
      menorrhagia: 0,
      postpartum: 0,
      muscle: 0,
      joint: 0,
      cns: 0,
      other: 0,
    },
    expect: { score: 0, riskLevel: 'low' },
    source: 'Rodeghiero F et al. J Thromb Haemost. 2010 — ISTH-SSC BAT domain scores 0–4; adult-male abnormal cutoff ≥4 (PMID 20626619).',
  },
  {
    calcId: 'isth-ssc-bat',
    description: 'Four domains of 1 in a male (epistaxis, cutaneous, minor wounds, oral cavity) = 4, positive',
    inputs: {
      sex: 'male',
      epistaxis: 1,
      cutaneous: 1,
      minorWounds: 1,
      oralCavity: 1,
      gi: 0,
      hematuria: 0,
      toothExtraction: 0,
      surgery: 0,
      menorrhagia: 0,
      postpartum: 0,
      muscle: 0,
      joint: 0,
      cns: 0,
      other: 0,
    },
    expect: { score: 4, riskLevel: 'high' },
    source: 'Elbatarny M et al. Haemophilia. 2014 — adult men abnormal if ISTH-BAT ≥4 (PMID 25196510).',
  },

  // ---------------------------------------------------------------- GLIM
  {
    calcId: 'glim-malnutrition',
    description: 'No phenotypic and no etiologic criteria → No GLIM malnutrition',
    inputs: {
      age: 60,
      bmi: 24,
      weightLoss: 'none',
      reducedMuscle: false,
      reducedIntake: false,
      inflammation: false,
    },
    expect: { score: 'No GLIM malnutrition', riskLevel: 'low' },
    source: 'Cederholm T et al. Clin Nutr. 2019 — GLIM requires ≥1 phenotypic AND ≥1 etiologic criterion (PMID 30172669).',
  },
  {
    calcId: 'glim-malnutrition',
    description: 'Moderate weight loss + reduced intake, BMI not severe → GLIM moderate',
    inputs: {
      age: 60,
      bmi: 24,
      weightLoss: 'moderate',
      reducedMuscle: false,
      reducedIntake: true,
      inflammation: false,
    },
    expect: { score: 'GLIM moderate', riskLevel: 'moderate' },
    source: 'Cederholm 2019 GLIM — moderate weight-loss band plus etiologic reduced intake = stage 1 (moderate).',
  },
  {
    calcId: 'glim-malnutrition',
    description: 'Severe weight loss + inflammation → GLIM severe',
    inputs: {
      age: 80,
      bmi: 23,
      weightLoss: 'severe',
      reducedMuscle: false,
      reducedIntake: false,
      inflammation: true,
    },
    expect: { score: 'GLIM severe', riskLevel: 'high' },
    source: 'Cederholm 2019 — severe weight-loss phenotypic criterion plus inflammation = GLIM stage 2.',
  },

  // ---------------------------------------------------------------- Leibovich 2018
  {
    calcId: 'leibovich-2018',
    description: 'pT1a (0) N0 (0) size 4 cm (0) grade 1–2 (0) no necrosis (0) = 0 low',
    inputs: { tStage: 0, nStage: 0, sizeCm: 4, grade: 0, necrosis: false },
    expect: { score: 0, riskLevel: 'low' },
    source: 'Leibovich BC et al. Eur Urol. 2018;73:772-80 — integer T/N/size/grade/necrosis; pT1a and grade 1–2 are 0 (PMID 29429895).',
  },
  {
    calcId: 'leibovich-2018',
    description: 'pT3a (4) + grade 4 (3) + necrosis (2) = 9 high; N0 size <10',
    inputs: { tStage: '3a', nStage: 0, sizeCm: 7, grade: 3, necrosis: true },
    expect: { score: 9, riskLevel: 'high' },
    source: 'Leibovich-style integer: pT3a = 4, grade 4 = 3, coagulative necrosis = 2.',
  },
];
